# actuator end-points should be served from a different port than the API/web content
management:
  port: 8008
  security:
    enabled: false
  # disable health check for tenant-specific features
  health:
    db:
      enabled: false

server:
  # tomcat settings for reasonable performance: adjust for tiny/huge configurations
  tomcat:
    max-connections: 0
    max-threads: 4
    accept-count: 10
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,text/csv

spring:
  cache:
    type: SIMPLE
    cache-names: subjects, subjectdefinitions

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  resources:
    chain:
      enabled: true
      gzipped: true

datasources:
  reporting_ro:
    url-parts:
      #This is the generic format of the connection URL protocol//[hosts][/database][?properties]
      protocol: "jdbc:mysql:"
      hosts: "${datasources.reporting_ro.url-server:localhost:3306}"
      database: "${datasources.reporting_ro.url-schema:reporting}"
      properties: "useSSL=${datasources.reporting_ro.use-ssl:false}\
                   &useLegacyDatetimeCode=${datasources.reporting_ro.use-legacy-datetime-code:false}\
                   &characterEncoding=${datasources.reporting_ro.character-encoding:utf8}\
                   &rewriteBatchedStatements=${datasources.reporting_ro.rewrite-batched-statements:true}\
                   &connectTimeout=${datasources.reporting_ro.connect-timeout:10000}\
                   &socketTimeout=${datasources.reporting_ro.socket-timeout:40000}\
                   "
    url: "${datasources.reporting_ro.url-parts.protocol}//${datasources.reporting_ro.url-parts.hosts}/${datasources.reporting_ro.url-parts.database}?${datasources.reporting_ro.url-parts.properties}"
    jdbcInterceptors: "QueryTimeoutInterceptor(queryTimeout=${datasources.reporting_ro.query-timeout:30})"
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    validationQueryTimeout: 10000
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    initialSize: 4
    maxActive: 10
    minIdle: ${datasources.reporting_ro.initialSize}
    maxIdle: ${datasources.reporting_ro.maxActive}
    removeAbandoned: false
    removeAbandonedTimeout: 60
    logAbandoned: false

  reporting_rw:
    url-parts:
      #This is the generic format of the connection URL protocol//[hosts][/database][?properties]
      protocol: "jdbc:mysql:"
      hosts: "${datasources.reporting_rw.url-server:localhost:3306}"
      database: "${datasources.reporting_rw.url-schema:reporting}"
      properties: "useSSL=${datasources.reporting_rw.use-ssl:false}\
                   &useLegacyDatetimeCode=${datasources.reporting_rw.use-legacy-datetime-code:false}\
                   &characterEncoding=${datasources.reporting_rw.character-encoding:utf8}\
                   &rewriteBatchedStatements=${datasources.reporting_rw.rewrite-batched-statements:true}\
                   &useCompression=${datasources.reporting_rw.use-compression:true}\
                   &connectTimeout=${datasources.reporting_rw.connect-timeout:10000}\
                   &socketTimeout=${datasources.reporting_rw.socket-timeout:40000}\
                   "
    url: "${datasources.reporting_rw.url-parts.protocol}//${datasources.reporting_rw.url-parts.hosts}/${datasources.reporting_rw.url-parts.database}?${datasources.reporting_rw.url-parts.properties}"
    jdbcInterceptors: "QueryTimeoutInterceptor(queryTimeout=${datasources.reporting_rw.query-timeout:30})"
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    validationQueryTimeout: 10000
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    initialSize: 4
    maxActive: 10
    minIdle: ${datasources.reporting_rw.initialSize}
    maxIdle: ${datasources.reporting_rw.maxActive}
    removeAbandoned: false
    removeAbandonedTimeout: 60
    logAbandoned: false

cloud:
  aws:
    credentials:
      #AWS credentials are necessary if reading assessment files from S3
      accessKey: ${rdw.aws.access.key:}
      secretKey: ${rdw.aws.secret.key:}
      instance-profile: false
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false

artifacts:
  #Root location of assessment files [s3://some-bucket/ | classpath: | etc]
  root: ${rdw.resource.root:"classpath:"}
  exam-item:
    directory: ${rdw.reporting.artifacts.exam.item.directory:local/items/Item-{0}/}
    file-name: item-{0}.xml

jwt:
  secret: ${rdw.reporting.jwt.secret:secret}

jdbc:
  retry:
    default:
      max-attempts: 3
      delay: 30
      multiplier: 2

reporting:
  school-year: 2019
  state:
    code: CA
    name: California

