# this app is expected to run inside the security perimeter so disable security for actuator end-points and,
# since those are the only end-points, switch to a less standard port using the main server.port config
management:
  port: 8008
  security:
    enabled: false

spring:
  batch:
    job:
      enabled: false
  cache:
    type: SIMPLE
    cache-names: translations
  cloud:
    stream:
      bindings:
        ReportExportExamsOut:
          content-type: application/json
          destination: ReportExportExams
          group: default
          producer:
            requiredGroups: default

        ReportExportExamsIn:
          content-type: application/json
          destination: ReportExportExams
          group: default

        ReportFetchStudentsOut:
          content-type: application/json
          destination: ReportFetchStudents
          group: default
          producer:
            requiredGroups: default

        ReportFetchStudentsIn:
          content-type: application/json
          destination: ReportFetchStudents
          group: default

        ReportGenerateForStudentsOut:
          content-type: application/json
          destination: ReportGenerateForStudents
          group: default
          producer:
            requiredGroups: default

        ReportGenerateForStudentsIn:
          content-type: application/json
          destination: ReportGenerateForStudents
          group: default
          consumer:
            concurrency: 2

        ReportCollateOut:
          content-type: application/json
          destination: ReportCollate
          group: default
          producer:
            requiredGroups: default

        ReportCollateIn:
          content-type: application/json
          destination: ReportCollate
          group: default

        ReportAggregateReportsOut:
          content-type: application/json
          destination: ReportAggregateReports
          group: default
          producer:
            requiredGroups: default

        ReportAggregateReportsIn:
          content-type: application/json
          destination: ReportAggregateReports
          group: default

        AggregateRequest:
          content-type: application/json
          group: default
          producer:
            requiredGroups: default

        AggregateResponse:
          content-type: application/json
          group: default
          producer:
            requiredGroups: default

  datasource:
    url: "\
      jdbc:mysql://${spring.datasource.url-server:localhost:3306}/${spring.datasource.url-schema:reporting}\
      ?useSSL=${spring.datasource.use-ssl:false}\
      &useLegacyDatetimeCode=${spring.datasource.use-legacy-datetime-code:false}\
      &characterEncoding=${spring.datasource.character-encoding:utf8}\
      &rewriteBatchedStatements=${spring.reporting_datasource.rewrite-batched-statements:true}\
      &connectTimeout=${spring.reporting_datasource.connect-timeout:10000}\
      &socketTimeout=${spring.reporting_datasource.socket-timeout:130000}\
      "
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    validationQueryTimeout: 10000
    driverClassName: com.mysql.jdbc.Driver
    initialize: false
    maxActive: 20
    initialSize: 4
    maxWait: 10000
    jdbcInterceptors: "QueryTimeoutInterceptor(queryTimeout=120)"

  jackson:
      default-property-inclusion: non_null
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
  thymeleaf:
    mode: HTML

cloud:
  aws:
    region:
      auto: false
      static: us-west-2
    # disable CloudFormation stuff
    stack:
      auto: false
    credentials:
      instance-profile: false

app:
  archive:
    root: file:///tmp/

  wkhtmltopdf:
    url: http://localhost:8082
    options:
      page-size: Letter
      zoom: 0.75

task:
# by default, all tasks are disabled for local dev environment; uncomment and set secrets/hosts to test.
#  remove-stale-reports:
##### at seconds: (0), minutes: (0), hour: (8), every day of month (*), every month (*), every day of week (*).
##### This runs at 8am GMT, regardless of the server's timezone setting
#    cron: 0 0 8 * * *
#    max-report-lifetime-days: 30
#    max-random-minutes: 20

jwt:
  secret: ${rdw.reporting.jwt.secret:secret}

reporting:
  school-year: 2018
  state:
    code: CA
    name: California
  # english-learners should be lep or elas
  english-learners:
    - elas