# docker-compose specs for rdw reporting service with the configuration server
# running in a container and MySQL running natively (outside the containers).
#
# The following environment variables MUST be set before running this spec:
#
# DATAWAREHOUSE_HOST - host running mysql with rdw reporting schema initialized
# For mac developers running mysql natively, something like:
#   $ export DATAWAREHOUSE_HOST=$(ipconfig getifaddr en0)
# This value may have to be reset when you change networks.
#
# CONFIG_SERVICE_REPO - git repo url, e.g. https://gitlab.com/fairwaytech/sbac-config-repo.git
# GIT_USER - user with rights to access CONFIG_SERVICE_REPO
# GIT_PASSWORD - password for GIT_USER
#
# This configuration maps the config folder as outlined in CONTRIBUTING.md and the application.yml file from the config
# server local-docker profile points to that folder so developers should be able to reuse the saml.jks file
# (NOTE: developers may have to explicitly share the /opt folder in Docker, Preferences, File Sharing)

version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  config-server:
    image: smarterbalanced/configuration-service:3.1.0.RELEASE
    container_name: config-server
    ports:
      - 8888:8888
    links:
      - rabbitmq
    environment:
      - CONFIG_SERVICE_REPO
      - ENCRYPT_KEY
      - GIT_USER
      - GIT_PASSWORD
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq:5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

  webapp:
    image: smarterbalanced/rdw-reporting-webapp
    ports:
      - 8080:8080
      - 8081:8008
    links:
      - config-server
      - report-processor-service
      - reporting-service
    environment:
      - spring.profiles.active=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888
      # need this until we have it on config server
      - zuul.routes.reporting-service.url=http://reporting-service:8080
      - zuul.routes.admin-service.url=http://admin-service:8080

    extra_hosts:
      - "dwhost:$DATAWAREHOUSE_HOST"

  admin-service:
    image: smarterbalanced/rdw-reporting-admin-webapp
    ports:
      - 8280:8080
      - 8208:8008
    volumes:
      - /tmp:/tmp
    links:
      - config-server
      - rabbitmq
    environment:
      - spring.profiles.active=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888
    extra_hosts:
      - "dwhost:$DATAWAREHOUSE_HOST"

  reporting-service:
    image: smarterbalanced/rdw-reporting-reporting-service
    ports:
      - 8180:8080
      - 8108:8008
    links:
      - config-server
    environment:
      - spring.profiles.active=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888
    extra_hosts:
      - "dwhost:$DATAWAREHOUSE_HOST"

  report-processor-service:
    image: smarterbalanced/rdw-reporting-report-processor
    ports:
      - 8085:8080
      - 8086:8008
    volumes:
      - /tmp:/tmp
    links:
      - config-server
      - rabbitmq
      - wkhtmltopdf
    environment:
      - spring.profiles.active=local-docker
      - CONFIG_SERVICE_ENABLED=true
      - CONFIG_SERVICE_URL=http://config-server:8888
    extra_hosts:
      - "dwhost:$DATAWAREHOUSE_HOST"

  wkhtmltopdf:
    image: smarterbalanced/wkhtmltopdf-image:latest
    ports:
      - 8082:80
